// export loadInfo from './loadInfo';
// export * as widget from './widget/index';
export loadAuth from './loadAuth';
export login from './login';
export logout from './logout';
export questions from './questions';
export matrix from './matrix';
export storeAnswer from './storeAnswer';
export storeProductName from './storeProductName';
export getAnswers from './getAnswers';
export setAllYes from './setAllYes';
export results from './results';
export repeat from './repeat';
