export Admin from './Admin/Admin';
export App from './App/App';
export Home from './Home/Home';
export Login from './Login/Login';
// export LoginSuccess from './LoginSuccess/LoginSuccess';
export NotFound from './NotFound/NotFound';
export Question from './Question/Question';
export Welcome from './Welcome/Welcome';
export Carcas from './Carcas/Carcas';
export Buttons from './Buttons/Buttons';
export Results from './Results/Results';
export ResultsCarcas from './ResultsCarcas/ResultsCarcas';
export QuestionInformation from './QuestionInformation/QuestionInformation';
